// Settings files for the languages, simply change the values here to change the language of your page

const frFR = {
    settingsTitle: "paramètres",
    navAudioTitle: "Audio",
    navGraphicsTitle: "Graphismes",
    navLanguageTitle: "Langue",
    navTutorialTitle: "Tutoriel",
    navGithubTitle: "Suivre le projet sur GitHub",
    instrumentChoice: "choix des sons",
    audioTrack: "piste audio",
    backgroundMusics: "musiques de fond",
    clearButton: "vider",
    activate: "activer",
    active: "actif",
    audioSettingsTitle: "Paramètres audio",
    graphicsSettingsTitle: "Paramètres graphiques",
    languageSettingsTitle: "Paramètres de langue",
    tutorialSettingsTitle: "Tutoriel",
    githubSettingsTitle: "GitHub",
    globalVolumeSwitchTitle: "Volume général",
    navigationVolumeSwitchTitle: "Effets de navigation",
    instrumentVolumeSwitchTitle: "Instruments",
    backgroundVolumeSwitchTitle: "Musiques de fond",
    blackWhitePlayerTitle: "Noir & blanc",
    whiteBlackPlayerTitle: "Blanc & noir",
    whiteRedPlayerTitle: "Blanc & rouge",
    blackYellowPlayerTitle: "Noir & jaune",
    graphicsPlayerCustomTitle: "Personnalisation du lecteur",
    kotomiName: "kotomi (ingénieure son)",
    tutorialMessage1: `Salut ! Je m'appelle Kotomi, je vais te guider dans le Genesis Studio ! Les zones mises en lumière sont celles que je vais t'expliquer à chaque fois... Cette fois-ci il est question du choix des sons, un aspect principal pour bien utiliser notre application ! (⩾﹏⩽) Le menu mis en valeur est le répertoire des sons de Genesis, c'est un menu scrollable qui compte donc tous nos sons, tu peux choisir de les prévisualiser avec le petit bouton "play" ou bien tu peux décider de les ajouter à ta composition en les attrapant avec ta souris !`,
    tutorialMessage2: `L'élément que tu vois en lumière est la piste audio !!! C'est super important ! C'est sur cette piste que tu viendras déposer les instruments choisis dans la partie précédente, il est possible de régler la piste en 3 modes différents, si tu souhaites être plus précis ou avoir une musique qui dure plus longtemps... Tu peux aussi vider tout d'un coup avec le bouton "vider" ! Enfin, un petit marqueur de temps passera une fois la musique lancée pour t'indiquer où elle en est.`,
    tutorialMessage3: `L'onglet "Musiques de fond" te permet de rajouter une musique de fond à ta composition, une fois que tu auras appuyé sur le bouton play, la musique se jouera en complément des instruments que tu auras disposé sur la piste, du moins si tu en as disposé... Il est d'ailleurs bon à noter que tu peux combiner les musiques de fond ! Pour les activer, il te suffit simplement d'appuyer sur le petit bouton "plus" à côté.`,
    tutorialMessage4: `Ce que tu vois là, c'est le lecteur Genesis ! Il te permettra de démarrer la lecture de ta composition, c'est à dire ta piste audio et les musiques de fond que tu pourrais avoir... Au fait, !!! Si tu appuies sur le bouton play, il se transformera en bouton pause, qui te permettra d'arrêter la lecture de ta composition ! Le lecteur Genesis est aussi intelligent, quand il joue un instrument de ta piste audio, le lecteur prendra la couleur de cet instrument pendant la durée du son de cet instrument !`,
    tutorialMessage5: `On termine ce tutoriel par l'onglet "Configurations" ! Tu retrouveras ici différentes musiques composées à l'aide de Genesis Studio que tu pourras appliquer à ta composition à l'aide du petit "plus" à côté. Fais attention cependant, puisque lorsque tu appliques une configuration, ce que tu aurais pu mettre avant sur la piste sera supprimé ! Et voilà, c'est la fin du tutoriel !!! Merci d'avoir écouté...`,
    yes: "oui",
    no: "non",
    next: "suivant",
    last: "précédent",
    finish: "terminer",
    shouldStartTutorial: "Lancer le tutoriel ?",
    shouldStartGithub: "Visiter la page GitHub ?",
    skip: "passer",
    configs: "Configurations",
    moreSoon: "Plus à venir."
}

const enUS = {
    settingsTitle: "settings",
    navAudioTitle: "Audio",
    navGraphicsTitle: "Graphics",
    navLanguageTitle: "Language",
    navTutorialTitle: "Tutorial",
    navGithubTitle: "Follow the project on Github",
    instrumentChoice: "instrument choice",
    audioTrack: "audio track",
    backgroundMusics: "background musics",
    clearButton: "clear",
    activate: "activate",
    active: "active",
    audioSettingsTitle: "Audio settings",
    graphicsSettingsTitle: "Graphic settings",
    languageSettingsTitle: "Language selection",
    tutorialSettingsTitle: "Tutorial",
    githubSettingsTitle: "GitHub",
    globalVolumeSwitchTitle: "Overall volume",
    navigationVolumeSwitchTitle: "Navigation effects",
    instrumentVolumeSwitchTitle: "Instruments",
    backgroundVolumeSwitchTitle: "Background musics",
    blackWhitePlayerTitle: "Black & white",
    whiteBlackPlayerTitle: "White & black",
    whiteRedPlayerTitle: "White & red",
    blackYellowPlayerTitle: "Black & yellow",
    graphicsPlayerCustomTitle: "Player customization",
    kotomiName: "kotomi (sound engineer)",
    tutorialMessage1: `Hello! My name is Kotomi, I will guide you inside the Genesis Studio! Each time the highlighted zone will be the one I'll explain you... So this time I will explain you the instrument choice section, a very important aspect to use our application correctly! (⩾﹏⩽) This menu is the sound repertory of Genesis, it's a scrollable menu that contains all our sounds, you can preplay them with the little "play" button or you can decide to add them to your composition by grabbing them with your mouse!`,
    tutorialMessage2: `The highlighted element is the audio track !!! It's super important ! It's on this track that you will place the different instruments chosen in the part we saw right before, it is possible to set the track in 3 different modes if you want to be more precise or having a musing that lasts longer... You can also empty the entire track with just one button using the "clear" button! Also, a little time mark will start running once the music has started to show you at what point it is.`,
    tutorialMessage3: `The "Background music" tab allows you to add a background music to your composition, once you have pressed the play button, the background music will be played in addition of the instruments you'll have placed on the track, at least if you decide to place some... It's also great to know that you can combine the background musics! To activate them, simply press the little "+" button next to them.`,
    tutorialMessage4: `What you're looking at is the Genesis player! It will allow you to start playing your composition: the sounds you may have in your track and the background musics you may have chosen... Oh, by the way, !!! If you press the play button, it will become a pause button, that will allow you to stop playing your composition! The Genesis player also is smart, when it plays a sound of your track, the player's background will become the played sound's color.`,
    tutorialMessage5: `We're concluding this tutorial by the "Configurations" tab! You will find here different musics composed using the Genesis Studio application that you will be able to apply to your composition using the little "+" button next to it. However, be aware that when you'll apply a configuration, your track and background musics will be reset! And here you have all the information you need !!! Thanks for listening...`,
    yes: "yes",
    no: "no",
    next: "next",
    last: "last",
    finish: "finish",
    shouldStartTutorial: "Begin the tutorial ?",
    shouldStartGithub: "Open GitHub ?",
    skip: "skip",
    configs: "Configurations",
    moreSoon: "More to come."
}

const jpJP = {
    settingsTitle: "設定",
    navAudioTitle: "オーディオ",
    navGraphicsTitle: "グラフィックス",
    navLanguageTitle: "言語",
    navTutorialTitle: "学習用",
    navGithubTitle: "Ｇｉｔｈｕｂフォローをする",
    instrumentChoice: "楽器のセレクトをする",
    audioTrack: "オーディオトラック",
    backgroundMusics: "バックグラウンドミュージック",
    clearButton: "晴れ",
    activate: "ｓｅｔ",
    active: "ｏｎ",
    audioSettingsTitle: "オーディオ設定",
    graphicsSettingsTitle: "グラフィックス設定",
    languageSettingsTitle: "言語設定",
    tutorialSettingsTitle: "学習用",
    githubSettingsTitle: "ＧｉｔＨｕｂ",
    globalVolumeSwitchTitle: "グローバル",
    navigationVolumeSwitchTitle: "航海",
    instrumentVolumeSwitchTitle: "楽器",
    backgroundVolumeSwitchTitle: "バックグラウンドミュージック",
    blackWhitePlayerTitle: "黒い と 白い",
    whiteBlackPlayerTitle: "白い と 黒い",
    whiteRedPlayerTitle: "白い と 赤い",
    blackYellowPlayerTitle: "黒い と 黄",
    graphicsPlayerCustomTitle: "プレーヤーのカスタマイズ",
    kotomiName: "琴美 (音響技師)",
    tutorialMessage1: `こんにちは！ 私はコトミです。ジェネシススタジオの案内をします！ 強調表示されたゾーンは毎回説明します...したがって、今回は、アプリケーションを正しく使用するための非常に重要な側面である機器選択セクションについて説明します。 （⩾﹏⩽）このメニューはGenesisのサウンドレパートリーであり、すべてのサウンドを含むスクロール可能なメニューです。小さな「再生」ボタンでそれらをプリプレイしたり、 マウス！`,
    tutorialMessage2: `ハイライトされた要素はオーディオトラックです!!! とても重要です！ 直前に見たパーツで選択したさまざまな楽器を配置するのはこのトラック上です。より正確にしたい場合や、長持ちするミューズを使用したい場合は、3つの異なるモードでトラックを設定できます... また、「クリア」ボタンを使用して、ボタン1つでトラック全体を空にすることもできます。 また、音楽がどの時点であるかを示し始めると、小さなタイムマークが実行を開始します。`,
    tutorialMessage3: `[バックグラウンドミュージック]タブでは、楽曲にバックグラウンドミュージックを追加できます。再生ボタンを押すと、少なくとも決定した場合、トラックに配置した楽器に加えてバックグラウンドミュージックが再生されます。 いくつかを配置する...バックグラウンドミュージックを組み合わせることができることを知っていることも素晴らしいです！ それらをアクティブにするには、単にそれらの横にある小さな「+」ボタンを押します。`,
    tutorialMessage4: `あなたが見ているのは創世記プレイヤーです！ それはあなたがあなたの作曲の再生を開始することを可能にします：あなたがあなたのトラックに持っているかもしれないサウンドとあなたが選んだかもしれないバックグラウンドミュージック...ああ、ところで、!!! 再生ボタンを押すと一時停止ボタンになり、作品の再生を停止できます！ ジェネシスプレーヤーもスマートです。トラックのサウンドを再生すると、プレーヤーの背景が再生されたサウンドの色になります。`,
    tutorialMessage5: `「設定」タブでこのチュートリアルを終了します！ Genesis Studioアプリケーションを使用して作成されたさまざまな音楽があり、その横にある小さな「+」ボタンを使用して作成に適用できます。 ただし、設定を適用すると、トラックとバックグラウンドミュージックがリセットされることに注意してください。 そしてここにあなたが必要とするすべての情報があります!!! 聞いてくれてありがとう...`,
    yes: "はい",
    no: "いいえ",
    next: "次",
    last: "前へ",
    finish: "終わる",
    shouldStartTutorial: "学習用を始める?",
    shouldStartGithub: "GitHubを開ける?",
    skip: "スキップ",
    configs: "コンフィグ",
    moreSoon: "もっと来て"
}